config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

resources :influencers
resources :tags
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/influencer.rb
class Influencer < ApplicationRecord
	has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :influencer
end

app/models/tag.rb
class Tag < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/influencers_controller.rb
class InfluencersController < ApplicationController

	def new
		@influencer = Influencer.new
	end

	def create
		@influencer = Influencer.new(influencer_params)
		scrapedata(influencer_params)
		redirect_to @influencer
	end

	def index
		@influencer = Influencer.all
	end
	
	def show
		@influencer = Influencer.find(params[:id])
	end

	def scrapedata(influencer_params)
		@page = Mechanize.new.get("https://www.instagram.com/" + influencer_params[:user])
  		pageContent
	end 

	def pageContent
		info = @page.body.split("<script type=\"text/javascript\">window._sharedData = ")[1]
		json = info.split(";</script>\n<script type=\"text/javascript\">window.__initialDataLoaded(window._sharedData);")[0]

		begin
  			parsed_data = JSON.parse(json)
		rescue JSON::ParserError => ex
			puts "A parsing error has occured with message #{ex.message} and status #{ex.status}"
		end

		addUser(parsed_data)
		getPosts(parsed_data)
	end

	def addUser(parsed_data)
		user = parsed_data["entry_data"]["ProfilePage"][0]["graphql"]["user"]["username"]
		biography = parsed_data["entry_data"]["ProfilePage"][0]["graphql"]["user"]["biography"]
		followers = parsed_data["entry_data"]["ProfilePage"][0]["graphql"]["user"]["edge_followed_by"]["count"]
		following = parsed_data["entry_data"]["ProfilePage"][0]["graphql"]["user"]["edge_follow"]['count']
		businessAccount = parsed_data["entry_data"]["ProfilePage"][0]["graphql"]["user"]["is_business_account"]
		businessCategory = parsed_data["entry_data"]["ProfilePage"][0]["graphql"]["user"]["business_category_name"]
		numberOfPosts = parsed_data["entry_data"]["ProfilePage"][0]["graphql"]["user"]["edge_owner_to_timeline_media"]["count"]
		page_info = parsed_data["entry_data"]["ProfilePage"][0]["graphql"]["user"]["edge_owner_to_timeline_media"]["page_info"]

		@newUser = Influencer.new(user: user, biography: biography, followers: followers, following: following, businessAcounnt: businessAccount, businessCategory: businessCategory, numberOfPosts: numberOfPosts, page_info: page_info)
		@newUser.save
	end

	def getPosts(parsed_data)
		user = parsed_data["entry_data"]["ProfilePage"][0]["graphql"]["user"]["username"]
		posts = parsed_data["entry_data"]["ProfilePage"][0]["graphql"]["user"]["edge_owner_to_timeline_media"]["edges"]

		posts.each do |post|
			caption = post["node"]["edge_media_to_caption"]["edges"][0]["node"]["text"]
			noOfComments = post["node"]["edge_media_to_comment"]["count"]
			postedTime = Time.at(post["node"]["taken_at_timestamp"]).to_datetime
			likes = post["node"]["edge_liked_by"]["count"]
			location = post["node"]["location"]
			ownerOfPost = post["node"]["owner"]
			isVideo = post["node"]["is_video"]
			videoViews = post["node"]["video_view_count"]

			posts = @newUser.posts.build(user: user, caption: caption, noOfComments: noOfComments, postedTime: postedTime, likes: likes, location: location, ownerOfPost: ownerOfPost, isVideo: isVideo, videoViews: videoViews)
			posts.save
		end 
	end

	def influencer_params
		params.require(:influencer).permit(:user)
	end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

	def new
		@tags = Tag.new
	end

	def create
		if Tag.exists?(tag_name: tags_params[:user])
			@tags = Tag.find_by(tag_name: tags_params[:user])
			redirect_to @tags
		else
			@tags = Tag.new(tags_params)
			scrapedata(tags_params)
			render "index"
			# redirect_to @tags
		end
	end

	def show
		@tags = Tag.find(tags_params[:id])
		# @tags = Tag.find_by(tag_name: tags_params[:user])
	end

	def index
		@tags = Tag.all.order("created_at DESC")
	end

	# private
	def tags_params
		params.require(:tag).permit(:user)
	end


	def scrapedata(user)
  		@page = Mechanize.new.get("https://www.instagram.com/tags/" + tags_params[:user])
  		pageContent
	end 

	def pageContent
		info = @page.body.split("<script type=\"text/javascript\">window._sharedData = ")[1]
		json = info.split(";</script>\n<script type=\"text/javascript\">window.__initialDataLoaded(window._sharedData);")[0]

		begin
  			parsed_data = JSON.parse(json)
		rescue JSON::ParserError => ex
			puts "A parsing error has occured with message #{ex.message} and status #{ex.status}"
		end

		tags = parsed_data["entry_data"]["TagPage"][0]["graphql"]["hashtag"]
		tags_info = tags["edge_hashtag_to_media"]["edges"]

		tag_name = tags["name"]
		popularity_of_tag = tags["edge_hashtag_to_media"]["count"]
		page_info = tags["edge_hashtag_to_media"]["page_info"]

		@tag = Tag.new(tag_name: tag_name, popularity_of_tag: popularity_of_tag, page_info: page_info)
		@tag.save

		tags_info.each_with_index do |tags, i|
			if tags_info[i]["node"]["edge_media_to_caption"]["edges"][0]["node"].empty? 
				comment= "there is no comment here"
			else
				comment = tags_info[i]["node"]["edge_media_to_caption"]["edges"][0]["node"]["text"]
			end
			comment_count = tags_info[i]["node"]["edge_media_to_comment"]["count"].to_s
			like_count = tags_info[i]["node"]["edge_liked_by"]["count"].to_s
			owner_id = tags_info[i]["node"]["owner"]["id"].to_s
			date_added = DateTime.strptime(tags_info[i]["node"]["taken_at_timestamp"].to_s,'%s').to_s
			accessibility_caption = tags_info[i]["node"]["accessibility_caption"].to_s
			userHandler = getOwner(owner_id)

			tags = Tag.new(user: userHandler, comment: comment, comment_count: comment_count, like_count: like_count, owner_id: owner_id, date_added: date_added, accessibility_caption: accessibility_caption)
			tags.save
		end
	end

	def getOwner(userId)
		url = HTTParty.get("https://instadigg.com/id/u/" + userId)
		instadigg ||= Nokogiri::HTML(url)

		if instadigg.css("div.detail p.website a[href]")[0].text.include? 'instagram.com/'
			user_name = instadigg.css("div.detail p.website a[href]")[0].text.split('instagram.com/')[1]
		elsif
			user_name = instadigg.css("div.detail p.website a[href]")[1].text.split('instagram.com/')[1]
		else
			user_name = userId
		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/influencers_helper.rb
module InfluencersHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/influencers/index.html.erb
<div class="header">
	<div class="logo">IRM</div
	><div class="title">Influencers</div>
</div>
<div class="page">
	<div class="menu">
		<a href="/influencers" class="active">Influencers</a>
		<a href="/tags">Tags</a>
		<a href="/influencers/new">Add Influencer</a>
		<a href="/tags/new">Add Tag</a>
	</div>
	<div class="content">
		<table>
			<tr>
				<td>User</td>
				<td>Biography</td>
				<td>Followers</td>
				<td>Following</td>
				<td> Follower ratio </td>
				<td> Engagement Rate </td>
				<td>Number Of Posts</td>
				<td>Business Account</td>
				<td>Business Category</td>
			</tr>
			<% @influencer.each do |f| %>
			<tr>
				<td>@<%=f.user %></td>
				<td><%= f.biography %></td>
				<td><%= f.followers %></td>
				<td><%= f.following %></td>
				<td><%= f.following.to_i == 0 ? 1 : f.followers.to_i / f.following.to_i %></td>

				<td><%= ((f.posts.average(:likes).to_f / f.followers.to_f) * 100).round(2)%> %</td>

				<td><%= f.numberOfPosts %></td>
				<td><%= f.businessAcounnt== 'f' ? 'No':'Yes' %></td>
				<td><%= f.businessCategory %></td>
				<td><%= link_to 'Show', influencer_path(f) %> </td>
			</tr>
			<% end %>
		</table>
	</div>
</div>

app/views/influencers/new.html.erb
<div class="header">
	<div class="logo">IRM</div
	><div class="title">Add New Influencer</div>
</div>
<div class="page">
	<div class="menu">
		<a href="/influencers">Influencers</a>
		<a href="/tags">Tags</a>
		<a href="/influencers/new" class="active">Add Influencer</a>
		<a href="/tags/new">Add Tag</a>
	</div>
	<div class="content">
		
		<%= form_for @influencer do |f| %>
			<p>
				<%= f.label :user %> <br>
				<%= f.text_field :user %>
			</p>

			<p>
				<%= f.submit %>
			</p>
		<% end %>

	</div>
</div>

app/views/influencers/show.html.erb
<div class="header">
	<div class="logo">IRM</div
	><div class="title">Posts by @<%= @influencer.user %></div>
</div>
<div class="page">
	<div class="menu">
		<a href="/influencers">Influencers</a>
		<a href="/tags">Tags</a>
		<a href="/influencers/new">Add Influencer</a>
		<a href="/tags/new">Add Tag</a>
	</div>
	<div class="content">
		
		<table>
			<tr>
				<td>Caption</td>
				<td>No Of Comments</td>
				<td>Likes</td>
				<td>Posted Time</td>

				<td>Location</td>
				<td>Owner Of Post</td>
				<td>Is Video</td>
				<td>Video Views</td>
			</tr>
			<% @influencer.posts.each do |f| %>
			<tr>
				<td><%= f.caption %></td>
				<td><%= f.noOfComments %></td>
				<td><%= f.likes %></td>
				<td><%= f.postedTime %></td>

				<td><%= f.location %></td>
				<td><%= f.ownerOfPost %></td>
				<td><%= f.isVideo %></td>
				<td><%= f.videoViews %></td>
			</tr>
			<% end %>
		</table>

	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Scrapper</title>
    <link href="https://fonts.googleapis.com/css?family=Work+Sans:400,500,600,700,800&display=swap" rel="stylesheet">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= yield %>
  </body>
</html>

app/views/tags/index.html.erb
<div class="header">
	<div class="logo">IRM</div
	><div class="title">Influencers recently posted with <%= @tags.first.tag_name %> tag (used <%= @tags.first.popularity_of_tag %> times)</div>
</div>
<div class="page">
	<div class="menu">
		<a href="/influencers">Influencers</a>
		<a href="/tags" class="active">Tags</a>
		<a href="/influencers/new">Add Influencer</a>
		<a href="/tags/new">Add Tag</a>
	</div>
	<div class="content">
		
		<table>
			<tr>
				<td>User</td>
				<td>Comment</td>
				<td>Comment Count</td>
				<td>Like Count</td>
				<td>Owner ID</td>
				<td>Date Added</td>
				<td>Accessibility Caption</td>
			</tr>
			<% @tags.all.each do |f| %>
			<tr>
				<td><%= link_to f.user, influencers_path(:influencer =>{:user => f.user}) , :method => :post %></td>
				<td><%= f.comment %></td>
				<td><%= f.comment_count %></td>
				<td><%= f.like_count %></td>
				<td><%= f.owner_id %></td>
				<td><%= f.date_added %></td>
				<td><%= f.accessibility_caption %></td>
			</tr>
			<% end %>
		</table>

	</div>
</div>

app/views/tags/new.html.erb
<div class="header">
	<div class="logo">IRM</div
	><div class="title">Find influencer by Hashtags</div>
</div>
<div class="page">
	<div class="menu">
		<a href="/influencers">Influencers</a>
		<a href="/tags">Tags</a>
		<a href="/influencers/new">Add Influencer</a>
		<a href="/tags/new" class="active">Add Tag</a>
	</div>
	<div class="content">
		
		<%= form_for @tags do |f| %>
			<p>
				<%= f.label :user %> <br>
				<%= f.text_field :user %>
			</p>

			<p>
				<%= f.submit %>
			</p>
		<% end %>

	</div>
</div>

app/views/tags/show.html.erb
<div class="header">
	<div class="logo">IRM</div>
	<div class="title">Influencers recently posted with times)</div>
</div>
<div class="page">
	<div class="menu">
		<a href="/influencers">Influencers</a>
		<a href="/tags" class="active">Tags</a>
		<a href="/influencers/new">Add Influencer</a>
		<a href="/tags/new">Add Tag</a>
	</div>
	<div class="content">
		
		<table>
			<tr>
				<td>User</td>
				<td>Comment</td>
				<td>Comment Count</td>
				<td>Like Count</td>
				<td>Owner ID</td>
				<td>Date Added</td>
				<td>Accessibility Caption</td>
			</tr>
			<% @tags.each do |f| %>
			<tr>
				<td><%= link_to f.user, influencers_path(:influencer =>{:user => f.user}) , :method => :post %></td>
				<td><%= f.comment %></td>
				<td><%= f.comment_count %></td>
				<td><%= f.like_count %></td>
				<td><%= f.owner_id %></td>
				<td><%= f.date_added %></td>
				<td><%= f.accessibility_caption %></td>
			</tr>
			<% end %>
		</table>

	</div>
</div>